# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 2.1.1 on 2018-09-06 12:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("main", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="build",
            name="metadata",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
